import { createVideo } from "@/redux/actions/videoAction";

export const routes = {
  eCommerce: {
    dashboard: '/ecommerce',
    products: '/ecommerce/products',
    createProduct: '/ecommerce/products/create',
    productDetails: (slug: string) => `/ecommerce/products/${slug}`,
    ediProduct: (slug: string) => `/ecommerce/products/${slug}/edit`,
    categories: '/ecommerce/categories',
    createCategory: '/ecommerce/categories/create',
    editCategory: (id: string) => `/ecommerce/categories/${id}/edit`,
    orders: '/ecommerce/orders',
    createOrder: '/ecommerce/orders/create',
    orderDetails: (id: string) => `/ecommerce/orders/${id}`,
    editOrder: (id: string) => `/ecommerce/orders/${id}/edit`,
    reviews: '/ecommerce/reviews',
    shop: '/ecommerce/shop',
    cart: '/ecommerce/cart',
    checkout: '/ecommerce/checkout',
    trackingId: (id: string) => `/ecommerce/tracking/${id}`,
  },
  // module: {
  //   // event: '/module/events',
  //   createEvents: '/events/create',
  //   eventDetails: (id: string) => `/events/${id}`,
  //   editEvent: (id: string) => `/events/${id}/edit`,
  //   viewEvent: (id: string) => `/events/${id}`,
  //   // news: '/module/news',
  //   createNews: '/news/create',
  //   newsDetails: (id: string) => `/news/${id}`,
  //   editNews: (id: string) => `/news/${id}/edit`,
  //   viewNews: (id: string) => `/news/${id}`,
  // },
  formations:'/formations',
  createFormations: '/formations/create',
  editFormations: (id: string) => `/formations/${id}/edit`,
  viewFormation: (id: string) => `/formations/${id}`,

  caseStudies:'/caseStudies',
  createCaseStudies: '/caseStudies/create',
  editCaseStudies: (id: string) => `/caseStudies/${id}/edit`,
  viewCaseStudies: (id: string) => `/caseStudies/${id}`,

  videos:'/videos',
  createVideos: '/videos/create',
  editVideos: (id: string) => `/videos/${id}/edit`,
  viewVideos: (id: string) => `/videos/${id}`,

  securityAlerts: '/securityAlerts',
  createSecurityAlerts: '/securityAlerts/create',
  editSecurityAlerts: (id: string) => `/securityAlerts/${id}/edit`,
  viewSecurityAlerts: (id: string) => `/securityAlerts/${id}`,

  event:'/events',
  news: '/news',
  createEvents: '/events/create',
    eventDetails: (id: string) => `/events/${id}`,
    editEvent: (id: string) => `/events/${id}/edit`,
    viewEvent: (id: string) => `/events/${id}`,
    createNews: '/news/create',
    newsDetails: (id: string) => `/news/${id}`,
    editNews: (id: string) => `/news/${id}/edit`,
    viewNews: (id: string) => `/news/${id}`,
  eventCalendar: '/event-calendar',
  widgets: {
    cards: '/widgets/cards',
    icons: '/widgets/icons',
    charts: '/widgets/charts',
    maps: '/widgets/maps',
    banners: '/widgets/banners',
  },
  tables: {
    basic: '/tables/basic',
    collapsible: '/tables/collapsible',
    enhanced: '/tables/enhanced',
    pagination: '/tables/pagination',
    search: '/tables/search',
    stickyHeader: '/tables/sticky-header',
  },
  forms: {
    profileSettings: '/forms/profile-settings',
    notificationPreference: '/forms/profile-settings/notification',
    personalInformation: '/forms/profile-settings/profile',
    newsletter: '/forms/newsletter',
  },
  profile: '/profile',
  welcome: '/welcome',
  comingSoon: '/coming-soon',
  accessDenied: '/access-denied',
  notFound: '/not-found',
  maintenance: '/maintenance',
  blank: '/blank',
  auth: {
    // signUp1: '/auth/sign-up-1',
    // signUp2: '/auth/sign-up-2',
    // signUp3: '/auth/sign-up-3',
    // signUp4: '/auth/sign-up-4',
    // signUp5: '/auth/sign-up-5',
    // sign in
    // signIn1: '/auth/sign-in-1',
    // signIn2: '/auth/sign-in-2',
    // signIn3: '/auth/sign-in-3',
    // signIn4: '/auth/sign-in-4',
    // signIn5: '/auth/sign-in-5',
    // forgot password
    // forgotPassword1: '/auth/forgot-password-1',
    // forgotPassword2: '/auth/forgot-password-2',
    // forgotPassword3: '/auth/forgot-password-3',
    // forgotPassword4: '/auth/forgot-password-4',
    // forgotPassword5: '/auth/forgot-password-5',
    // OTP
    otp1: '/auth/otp-1',
    otp2: '/auth/otp-2',
    otp3: '/auth/otp-3',
    otp4: '/auth/otp-4',
    otp5: '/auth/otp-5',
  },
  signIn: '/signin',
};
